#!/usr/bin/python
# -*- coding: UTF-8 -*-
 
class isLeagueMember:        # 定义父类
   parentAttr = 100
   def canMembers(self):
      print "调用父类构造函数"
 
   def leagueMethod(self):
      print '调用父类方法'
 
   def setAttr(self, attr):
      isLeagueMember.leagueAttr = attr
 
   def getAttr(self):
      print "父类属性 :", isLeagueMember.leagueAttr
 
class isYongPioneers(isLeagueMember): # 定义子类
   def canRecite(self):
      print "调用子类构造方法"
 
   def yongMethod(self):
      print '调用子类方法'
 
c = isYongPioneers()          # 实例化子类
c.yongMethod()      # 调用子类的方法
c.leagueMethod()     # 调用父类方法
c.setAttr(200)       # 再次调用父类的方法 - 设置属性值
c.getAttr()          # 再次调用父类的方法 - 获取属性值
